import os
import requests
import datetime
import pytz
import yfinance as yf
import time
from newsapi import NewsApiClient

# === 設定 ===
OPENROUTER_API_KEY = os.getenv("GEMINI_API_KEY") 
NEWS_API_KEY = os.getenv("NEWS_API_KEY")
DISCORD_WEBHOOK_URL = os.getenv("DISCORD_WEBHOOK_URL")

# 無料モデルの優先順位リスト
FREE_MODELS = [
    "google/gemini-2.0-flash-exp:free",
    "meta-llama/llama-3.3-70b-instruct:free",
    "mistralai/pixtral-12b:free",
    "qwen/qwen-2.5-72b-instruct:free"
]

def get_market_data():
    targets = {"NVDA": "NVIDIA", "^SOX": "半導体指数", "ES=F": "S&P500先物", "NQ=F": "ナスダック100先物"}
    report_data = ""
    for ticker, name in targets.items():
        try:
            t = yf.Ticker(ticker)
            hist = t.history(period="5d")
            if len(hist) < 2: continue
            curr = hist.iloc[-1]
            prev = hist.iloc[-2]
            change_pct = ((curr['Close'] - prev['Close']) / prev['Close']) * 100
            report_data += f"{name}: {curr['Close']:.2f} ({change_pct:+.2f}%)\n"
        except: pass
    return report_data

def fetch_news():
    newsapi = NewsApiClient(api_key=NEWS_API_KEY)
    jst = pytz.timezone('Asia/Tokyo')
    now = datetime.datetime.now(jst)
    start_date = (now - datetime.timedelta(days=2)).strftime('%Y-%m-%d')
    collected = ""
    for q in ["NVIDIA", "US Stock Market"]:
        try:
            res = newsapi.get_everything(q=q, language='en', sort_by='publishedAt', from_param=start_date, page_size=3)
            for art in res.get('articles', []):
                collected += f"・{art['title']} ({art['publishedAt']})\n"
        except: pass
    return collected

def call_ai_with_retry(prompt):
    """ 利用可能な無料モデルを順に試し、成功するまで繰り返す """
    for model_name in FREE_MODELS:
        try:
            print(f"Trying model: {model_name}...")
            res = requests.post(
                "https://openrouter.ai/api/v1/chat/completions",
                headers={
                    "Authorization": f"Bearer {OPENROUTER_API_KEY}",
                    "Content-Type": "application/json",
                    "HTTP-Referer": "https://github.com/my-stock-ai"
                },
                json={
                    "model": model_name,
                    "messages": [{"role": "user", "content": prompt}],
                    "temperature": 0.7
                },
                timeout=120
            )
            data = res.json()
            if 'choices' in data:
                return data['choices'][0]['message']['content'], model_name
            else:
                print(f"Model {model_name} failed: {data.get('error', {}).get('message')}")
                time.sleep(5) # 短い待機
        except Exception as e:
            print(f"Exception with {model_name}: {e}")
            continue
    return None, None

def main():
    jst = pytz.timezone('Asia/Tokyo')
    now = datetime.datetime.now(jst)
    is_morning = 5 <= now.hour <= 11
    market_info = get_market_data()
    news_info = fetch_news()

    prompt = f"""
【最優先】現在は2026年1月12日です。2024年の古い情報は禁止。
プロの米国株ストラテジストとして、読むのに10分かかる圧倒的長文（約5000文字）で執筆せよ。

【構成必須】
1. **2026年最新ニュース影響度格付け**：詳細解説。
2. **NVIDIA別枠分析**：2026年1月の最新データに基づくテクニカル。
3. **半導体/AI/対中政策別枠**：地政学と技術動向。
4. **{'朝の答え合わせ' if is_morning else '今夜のシナリオ予想'}**：論理的根拠を提示。
5. **実際のニュース日付一覧**：2026/01であることを明記。

データ: {market_info}
ニュース: {news_info}
絵文字多用、情熱的なトーンで。
"""

    report, used_model = call_ai_with_retry(prompt)

    if report and DISCORD_WEBHOOK_URL:
        footer = f"\n\n*(Generated by {used_model})*"
        full_text = report + footer
        chunks = [full_text[i:i+1900] for i in range(0, len(full_text), 1900)]
        for chunk in chunks:
            requests.post(DISCORD_WEBHOOK_URL, json={"content": chunk})
            time.sleep(2)
    else:
        requests.post(DISCORD_WEBHOOK_URL, json={"content": "⚠️ 全ての無料モデルが制限中でした。時間を空けて再実行されます。"})

if __name__ == "__main__":
    main()
